FROM node:14.18-alpine

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY package.json package.json

RUN apk update && apk add chromium \
    && npm install \
    && npm install -g @angular/cli \
    && npm audit fix

COPY . .

CMD npm run start -- --host 0.0.0.0 --port 443 --ssl true --ssl-cert "/certs/cert.pem" --ssl-key "/certs/key.pem"
